// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_api.Context;

#nullable disable

namespace dotnet_api.Migrations
{
    [DbContext(typeof(dotnet_apiContext))]
    [Migration("20221107233713_migration")]
    partial class migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnet_api.Models.Entities.Files", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<byte[]>("DataFiles")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("DataFiles");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FileType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("dotnet_api.Models.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Login");

                    b.Property<short>("Nivel")
                        .HasColumnType("smallint")
                        .HasColumnName("Nivel");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Password");

                    b.Property<short>("RelCF")
                        .HasColumnType("smallint")
                        .HasColumnName("RelCF");

                    b.Property<short>("RelCFTOT")
                        .HasColumnType("smallint")
                        .HasColumnName("RelCFTOT");

                    b.Property<short>("RelNF")
                        .HasColumnType("smallint")
                        .HasColumnName("RelNF");

                    b.Property<short>("RelNFICMS")
                        .HasColumnType("smallint")
                        .HasColumnName("RelNFICMS");

                    b.Property<short>("RelNFICMSST")
                        .HasColumnType("smallint")
                        .HasColumnName("RelNFICMSST");

                    b.Property<short>("RelNFQTD")
                        .HasColumnType("smallint")
                        .HasColumnName("RelNFQTD");

                    b.Property<short>("RelNFQTDUF")
                        .HasColumnType("smallint")
                        .HasColumnName("RelNFQTDUF");

                    b.Property<short>("RelNFUF")
                        .HasColumnType("smallint")
                        .HasColumnName("RelNFUF");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
